name: flutter_netdata
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.6.0
  http: ^0.12.0+2
  firebase_auth: ^0.8.4+5
  google_sign_in: ^4.0.1+3
  firebase_core: ^0.3.4
  firebase_analytics: ^2.1.1+3
  cloud_firestore: ^0.10.1
  rxdart: ^0.22.0
  image_picker: ^0.6.0+2
  firebase_storage: ^2.1.1+2
  uuid: ^1.0.1
  ssh: ^0.0.3
  path_provider: ^1.1.0
  line_icons: ^0.2.0
  tree_view: ^0.0.5
  google_maps_flutter: ^0.5.15

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
